DEFAULT_GOODBYE_MESSAGES = [
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\n{first} will be missed.",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\n{first} just went offline.",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\n{first} has left the lobby.",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\n{first} has left the clan.",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\n{first} has left the game.",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\n{first} has fled the area.",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\n{first} is out of the running.",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nNice knowing ya, {first}!",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nIt was a fun time {first}.",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nWe hope to see you again soon, {first}.",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nI donut want to say goodbye, {first}.",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nGoodbye {first}! Guess who's gonna miss you :')",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nGoodbye {first}! It's gonna be lonely without ya.",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nPlease don't leave me alone in this place, {first}!",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nGood luck finding better shit-posters than us, {first}!",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nYou know we're gonna miss you {first}. Right? Right? Right?",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nCongratulations, {first}! You're officially free of this mess.",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\n{first}. You were an opponent worth fighting.",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nYou're leaving, {first}? Yare Yare Daze.",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nBring him the photo",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nGo outside!",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nAsk again later",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nThink for yourself",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nQuestion authority",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nYou are worshiping a sun god",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nDon't leave the house today",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nGive up!",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nMarry and reproduce",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nStay asleep",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nWake up",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nLook to la luna",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nSteven lives",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nMeet strangers without prejudice",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nA hanged man will bring you no luck today",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nWhat do you want to do today?",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nYou are dark inside",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nHave you seen the exit?",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nGet a baby pet it will cheer you up.",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nYour princess is in another castle.",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nYou are playing it wrong give me the controller",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nTrust good people",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nLive to die.",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nWhen life gives you lemons reroll!",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nWell, that was worthless",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nI fell asleep!",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nMay your troubles be many",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nYour old life lies in ruin",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nAlways look on the bright side",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nIt is dangerous to go alone",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nYou will never be forgiven",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nYou have nobody to blame but yourself",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nOnly a sinner",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nUse bombs wisely",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nNobody knows the troubles you have seen",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nYou look fat you should exercise more",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nFollow the zebra",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nWhy so blue?",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nThe devil in disguise",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nGo outside",
    "—🔥••÷[  ӄʟǟա🦀ʀօɮօȶ  ]÷••🔥—\nAlways your head in the clouds",
]
DEFAULT_GOODBYE = "Nice knowing ya!"
